# Generated by Django 4.1.3 on 2022-12-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birtsday',
            new_name='birthday',
        ),
    ]
