# Generated by Django 4.1.3 on 2022-12-18 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contract_money_in_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='from_date',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
    ]
