# Generated by Django 4.1.3 on 2022-12-18 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contract_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
