# Generated by Django 4.1.3 on 2022-12-19 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contract_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='from_date',
            field=models.DateField(default=datetime.date(2022, 12, 19)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='to_date',
            field=models.DateField(default=datetime.date(2023, 1, 2)),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
